### ISSUE TITLE
PutObject operation: Access Denied

### ISSUE THREAD

**Issue by esalling23** [esalling23/roscoe-thanksgivings#1]
Error on AWS create object. 

```
Internal Server Error: /admin/api/photo/add/
Traceback (most recent call last):
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "/Users/gaboston/Developer/roscoe-thanksgivings/api/models/photo.py", line 26, in save
    super().save(*args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/base.py", line 886, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/base.py", line 923, in _do_insert
    return manager._insert(
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1376, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1319, in as_sql
    value_rows = [
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1320, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1320, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1271, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/storages/backends/s3boto3.py", line 451, in _save
    obj.upload_fileobj(content, ExtraArgs=params)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/boto3/s3/inject.py", line 619, in object_upload_fileobj
    return self.meta.client.upload_fileobj(
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/gaboston/.local/share/virtualenvs/roscoe-thanksgivings-qBjjbA0-/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
[15/Sep/2021 02:15:51] "POST /admin/api/photo/add/ HTTP/1.1" 500 236054
```

All research says to check the bucket policy and ensure I have `PutObjectAcl`:
> Note: I replaced the account-id with X below

```
{
    "Version": "2012-10-17",
    "Id": "Policy1605746642773",
    "Statement": [
        {
            "Sid": "Stmt1605746623828",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::x:user/roscoe-user"
            },
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::roscoethanksgiving/*",
                "arn:aws:s3:::roscoethanksgiving"
            ]
        }
    ]
}
```

Cloud trail shows this failing JSON:

```
{
   "eventVersion": "1.08",
   "userIdentity": {
        "type": "Root",
        "principalId": "x",
        "arn": "arn:aws:iam::x:root",
        "accountId": "x",
        "accessKeyId": "<access-key>",
        "sessionContext": {
             "sessionIssuer": {},
             "webIdFederationData": {},
             "attributes": {
                    "mfaAuthenticated": "false",
                    "creationDate": "2021-09-14T14:16:38Z"
              }
         }
   },
   "eventTime": "2021-09-15T01:03:49Z",
   "eventSource": "iam.amazonaws.com",
   "eventName": "GetAccountPasswordPolicy",
   "awsRegion": "us-east-1",
   "sourceIPAddress": "71.232.76.46",
   "userAgent": "console.amazonaws.com",
   "errorCode": "NoSuchEntityException",
   "errorMessage": "The Password Policy with domain name X cannot be found.",
   "requestParameters": null,
   "responseElements": null,
   "requestID": "f3d842f4-855c-4061-8364-7dd9f6c2020e",
   "eventID": "ea0bd217-efcc-494b-af54-af393d469660",
   "readOnly": true,
   "eventType": "AwsApiCall",
   "managementEvent": true,
   "eventCategory": "Management",
   "recipientAccountId": "x"
},
```

`eventName`: https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetAccountPasswordPolicy.html

>NoSuchEntity
>The request was rejected because it referenced a resource entity that does not exist. The error message describes the resource.
>
>HTTP Status Code: 404

Getting a 500 but that may be due to how boto3 is interpreting the error. 

The user making the request seems to be the root, not the `roscoe-user`,

**Comment by esalling23** [comment]
Update: I believe I was struggling to locate/find the correct logs with CloudTrail, and have now set it up correctly. Here's an example of the JSON provided, error name `AccessDenied` and error message "Access Denied". 

```
{
   "Records": [
        {
             "eventVersion": "1.08",
             "userIdentity": {
                  "type": "IAMUser",
                   "principalId": "AIDAWVECR3OU5OA2GB5IP",
                   "arn": "arn:aws:iam::x:user/roscoe-user",
                   "accountId": "x",
                   "accessKeyId": "<access-key-id>",
                   "userName": "roscoe-user"
             },
             "eventTime": "2021-09-15T19:27:31Z",
             "eventSource": "s3.amazonaws.com",
             "eventName": "PutObject",
             "awsRegion": "us-east-1",
             "sourceIPAddress": "71.232.76.46",
             "userAgent": "[Boto3/1.16.25 Python/3.9.6 Darwin/18.7.0 Botocore/1.19.25 Resource]",
             "errorCode": "AccessDenied",
             "errorMessage": "Access Denied",
             "requestParameters": {
                  "bucketName": "roscoethanksgiving",
                  "Host": "roscoethanksgiving.s3.amazonaws.com",
                  "x-amz-acl": "public-read",
                  "key": "IMG_3575.JPG"
             },
             "responseElements": null,
             "additionalEventData": {
                  "SignatureVersion": "SigV4",
                  "CipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
                  "bytesTransferredIn": 0,
                  "AuthenticationMethod": "AuthHeader",
                  "x-amz-id-2": "kJEaGvjAkxIIbIA5OXceRA1ZenwUnAziiyDEzljt4KqTdUSu6VR9YYGAdXpwW4h07eFihPYHBb0=",
                  "bytesTransferredOut": 243
             },
             "requestID": "1W0Y1RND3C740F2T",
             "eventID": "472785f4-448c-43f5-b5e0-9fadafb76f33",
             "readOnly": false,
             "resources": [
                  {
                      "type": "AWS::S3::Object",
                      "ARN": "arn:aws:s3:::roscoethanksgiving/IMG_3575.JPG"
                  },
                 {
                     "accountId": "x",
                     "type": "AWS::S3::Bucket",
                     "ARN": "arn:aws:s3:::roscoethanksgiving"
                  }
             ],
            "eventType": "AwsApiCall",
             "managementEvent": false,
             "recipientAccountId": "x",
             "eventCategory": "Data"
         }
     ]
}
```
